---
name: Rocket Fuel to AcmeERP
description: >
  After a rocket is launched, fuel data is sent to this integration via a
  trigger payload.  The payload is verified, fuel data is converted from pounds
  to gallons, and XML-formatted data is sent to the customer's AcmeERP instance.

requiredConfigVars:
  acmeErpFuelEndpoint: https://postman-echo.com/post
  secret: secret

trigger:
  name: Webhook Trigger
  description: Expects a data payload and X-Progix-Signature header

steps:
  - name: Verify Signature
    description: Verify that the X-Progix-Signature is valid
    action:
      key: verifySignature
      componentKey: progix-sig-check
    inputs:
      signature:
        type: reference
        value: webhookTrigger.results.headers.x-progix-signature
      body:
        type: reference
        value: webhookTrigger.results.rawBody.data
      secret:
        type: configVar
        value: secret

  - name: Compute Gallons Fuel
    description: Convert incoming fuel data from pounds to gallons
    action:
      key: runCode
      componentKey: code
    inputs:
      code:
        type: value
        value: |
          module.exports = async (context, { webhookTrigger }) => {
            const gallonsToPoundsConversion = {
              Hydrazine: 8.38,
              Kerosene: 6.68,
              Nitromethane: 9.49,
              O2: 9.52,
            };
            const fuelUsed = webhookTrigger.results.body.data.fuelUsed;
            return {
              data: {
                fuelGallonsUsed: fuelUsed.reduce((obj, item) => {
                  return {
                    ...obj,
                    [item.type]: item.pounds / gallonsToPoundsConversion[item.type],
                  };
                }, {}),
              },
            };
          };

  - name: Convert JSON to XML
    description:
      Convert JSON data from the code component to the XML that AcmeERP expects.
    action:
      key: jsonToXml
      componentKey: change-data-format
    inputs:
      data:
        type: reference
        value: computeGallonsFuel.results.fuelGallonsUsed

  - name: Send Data to AcmeERP
    description: HTTP POST XML data to AcmeERP endpoint using OAuth 2.0
    action:
      key: httpPost
      componentKey: http
    inputs:
      url:
        type: configVar
        value: acmeErpFuelEndpoint
      data:
        type: reference
        value: convertJsonToXml.results
      responseType:
        type: value
        value: text
